name: build

permissions:
  contents: write
  repository-projects: write

on:
  workflow_dispatch:
    branches: [dev]

jobs:
  build:
    name: build-wasm
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: node
      uses: actions/setup-node@v6
      with:
        node-version: "24"
    - name: Install pnpm
      uses: pnpm/action-setup@v6
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Install build dependencies
      run: sudo apt install -y clang-18 lld-18 binaryen
    - run: |
        git pull
        cur=$(git rev-parse --abbrev-ref HEAD)
        echo "current branch is $cur."
        if [ "$cur" != "dev" ]; then
          echo "err : not dev branch"
          exit 1
        fi
        git config user.name github-actions
        git config user.email github-actions@github.com
        git submodule update --init --recursive
        make -C src clean
        pnpm install
        pnpm run build:she_c.js
        pnpm run build:browser
        pnpm test
        sha256sum src/she_c.js browser/she.js
        git add -f src/she_c.js browser/she.js
        changes=$(git diff --staged --numstat | wc -l)
        if [[ $changes -gt 0 ]]
        then
          git commit -m "build: she_c.js is generated by GitHub Action"
          git push origin dev
        fi
