name: test
on: [push]

permissions:
  contents: read

jobs:
  build:
    name: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: node
      uses: actions/setup-node@v6
      with:
        node-version: "24"
    - name: Install pnpm
      uses: pnpm/action-setup@v6
    - run: pnpm install
    - run: pnpm test
